---
title: "VISMCL"
author: "Liwen Zhuang"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{VISMCL}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
Vismcl is a cluster visualization tool, it supports user-defined cluster name and different way to highlight specific cluster, user can also adjust the number of clusters he/she wants to show.

This package also include a user-friendly shiny app interface.Just type <code> runvismclApp() </code> in console

Hope this package can help you view cluster in a better way.:)


## Input Info
Input for VISMCL should be a text file(usually produced by MCL) path,the file need to be:

- Have no headings or tail
- Elements in one cluster are stayed in one line, seperated by tab
- Include a newline at the end of the file.


## Functions

- vismcl：This is the basic function used to plot clusters.It will print the dataframe created from the file.
- vismclL：This is specifically designed for large input file,it adds a new attribute filterN, this limit the number. Also when using vismclL, the dataframe will not be printed as vismcl do. Except these minor differences,the output is the same as vismcl.
- runvismclApp：This function use shiny app to create a user-friendly interface.
